routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('products', ProductController::class);
Route::get('product/soft/delete/{id}', [ProductController::class, 'softDelete'])
    ->name('soft.delete');

Route::get('product/trash', [ProductController::class, 'trashproducts'])
    ->name('product.trash');

Route::get('product/back/from/trash{id}', [ProductController::class, 'backSoftDelete'])
    ->name('product.back.from.trash');

Route::get('product/delete/from/database{id}', [ProductController::class, 'deleteForEver'])
    ->name('product.delete.from.database');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected  $fillable = [
        'name', 'price', 'detail',
    ];
    protected $dates = ['deleted_at'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    //to show requeird  product form user
    public function index()
    {
        $products = Product::latest()->paginate(4);
        return view('product.index', compact('products'));
    }

    public function trashproducts()
    {
        //     $products = Product::withTrashed()->latest()->paginate(4);
        $products = Product::onlyTrashed()->latest()->paginate(4);
        return view('product.trash', compact('products'));
    }

    //to create a new product
    public function create()
    {
        return view('product.create');
    }

    //to store information a new create product
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'price' => 'required',
            'detail' => 'required'
        ]);
        $product = Product::create($request->all());
        return redirect()->route('products.index')->with('success', 'Product added successfully');
    }
    //to show all products
    public function show(Product $product)
    {
        return view('product.show', compact('product'));
    }

    //to edit the product
    public function edit(Product $product)
    {
        return view('product.edit', compact('product'));
    }


    public function update(Request $request, Product $product)
    {
        $request->validate([
            'name' => 'required',
            'price' => 'required',
            'detail' => 'required'
        ]);
        $product->update($request->all());
        return redirect()->route('products.index')->with('success', 'Product updated successfully');
    }


    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()->route('products.index')->with('success', 'Product deleted successfully');
    }
    public function softDelete($id)
    {
        $product = Product::find($id)->delete();
        return redirect()->route('products.index')->with('success', 'Product deleted successfully');
    }

    public function backSoftDelete($id)
    {
        $product = Product::onlyTrashed()->where('id', $id)->first()->restore();
        return redirect()->route('products.index')->with('success', 'Product deleted successfully');
    }
    public function deleteForEver($id)
    {
        $product = Product::onlyTrashed()->where('id', $id)->forceDelete();
        return redirect()->route('product.trash')->with('success', 'Product deleted successfully');
    }
}

resources/views/product/create.blade.php
@extends('product.layouts')

@section('content')
    <div class="container" style="padding-top : 12%">
        <div class="card ">

            <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's
                    content.</p>
            </div>
        </div>

    </div>
    <div class="container" style="padding-top : 2%">
        <form action="{{ route('products.store') }}" method="POST">
            @csrf
            <div class="form-group">
                <label for="exampleFormControlInput1"> Name</label>
                <input type="text" name="name" class="form-control" placeholder="product name ">
            </div>

            <div class="form-group">
                <label for="exampleFormControlInput1"> Name</label>
                <input type="text" name="price" class="form-control" placeholder="product price ">
            </div>

            <div class="form-group">
                <label for="exampleFormControlSelect1">Details</label>
                <textarea class="form-control" name="detail" rows="3"></textarea>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>


        </form>
    </div>
@endsection

resources/views/product/edit.blade.php
@extends('product.layouts')

@section('content')
    <div class="container" style="padding-top : 12%">
        <div class="card ">

            <div class="card-body">
                <p class="card-text"> Product Name : {{ $product->name }}</p>
            </div>
        </div>

    </div>
    <div class="container" style="padding-top : 2%">
        <form action="{{ route('products.update', $product->id) }}" method="POST">
            @csrf
            @method('PUT')

            <div class="form-group">
                <label for="exampleFormControlInput1"> Name</label>
                <input type="text" name="name" value="{{ $product->name }}" class="form-control"
                    placeholder="product name ">
            </div>

            <div class="form-group">
                <label for="exampleFormControlInput1"> Name</label>
                <input type="text" name="price" value="{{ $product->price }}" class="form-control"
                    placeholder="product price ">
            </div>

            <div class="form-group">
                <label for="exampleFormControlSelect1">Details</label>
                <textarea class="form-control" name="detail" rows="3">{!! $product->detail !!}</textarea>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Update</button>
            </div>


        </form>
    </div>
@endsection

resources/views/product/index.blade.php
@extends('product.layouts')

@section('content')
    <div class="jumbotron container">


        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-primary btn-lg" href="{{ route('products.create') }}" role="button">Create</a>
        <a class="btn btn-primary btn-lg" href="{{ route('product.trash') }}" role="button">trash</a>
    </div>

    <div class="container">
        @if ($message = Session::get('success'))
            <div class="alert alert-primary" role="alert">
                {{ $message }}
            </div>
        @endif
    </div>


    <div class="container">

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Product name </th>
                    <th scope="col">Product price</th>
                    <th scope="col" stayle="width :200px">Action</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $i = 0;
                @endphp
                @foreach ($products as $item)
                    <tr>
                        <th scope="row">{{ ++$i }}</th>
                        <td>{{ $item->name }}</td>
                        <td>{{ $item->price }} SR</td>
                        <td>
                            <div class="row">
                                <div class="col-sm">
                                    <a class="btn btn-success" href="{{ route('products.edit', $item->id) }}">Edit</a>
                                </div>
                                <div class="col-sm">
                                    <a class="btn btn-primary" href="{{ route('products.show', $item->id) }}">Show</a>
                                </div>
                                <div class="col-sm">
                                    <a class="btn btn-warning" href="{{ route('soft.delete', $item->id) }}">SoftDelete</a>
                                {{-- </div>
                                <div class="col-sm">
                                    <form action="{{ route('products.destroy', $item->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger" type="submit">Delete</button>
                                    </form>
                                </div> --}}
                            </div>


                        </td>
                    </tr>
                @endforeach


            </tbody>
        </table>
        {!! $products->links() !!}
    </div>
@endsection

resources/views/product/layouts.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>Products</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
</head>

<body>

    @yield('content')

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous">
    </script>
</body>

</html>

resources/views/product/show.blade.php
@extends('product.layouts')

@section('content')
    <div class="container" style="padding-top : 12%">
        <div class="card ">

            <div class="card-body">
                <p class="card-text"> Product Name : {{ $product->name }}</p>
            </div>
        </div>

    </div>
    <div class="container" style="padding-top : 2%">


        <div class="form-group">
            <label for="exampleFormControlInput1"> {{ $product->name }}</label>

        </div>

        <div class="form-group">
            <label for="exampleFormControlInput1"> {{ $product->price }} SR</label>


        </div>

        <div class="form-group">
            <label for="exampleFormControlSelect1">{!! $product->detail !!}</label>

        </div>
        <form action="{{ route('products.index', $product->id) }}">
            <div class="form-group">
                <button type="submit" class="btn btn-primary">back</button>
            </div>
        </form>


    </div>
@endsection

resources/views/product/trash.blade.php
@extends('product.layouts')

@section('content')
    <div class="jumbotron container">


        <p>Trash products.</p>
        <a class="btn btn-primary btn-lg" href="{{ route('products.index') }}" role="button">Home</a>
    </div>




    <div class="container">

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Product name </th>
                    <th scope="col">Product price</th>
                    <th scope="col" stayle="width :200px">Action</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $i = 0;
                @endphp
                @foreach ($products as $item)
                    <tr>
                        <th scope="row">{{ ++$i }}</th>
                        <td>{{ $item->name }}</td>
                        <td>{{ $item->price }} SR</td>
                        <td>
                            <div class="row">

                                <div class="col-sm">
                                    <a class="btn btn-primary"
                                        href="{{ route('product.back.from.trash', $item->id) }}">back</a>
                                </div>
                                <div class="col-sm">
                                    <a class="btn btn-danger"
                                        href="{{ route('product.delete.from.database', $item->id) }}">delete</a>
                                </div>


                            </div>


                        </td>
                    </tr>
                @endforeach


            </tbody>
        </table>
        {!! $products->links() !!}
    </div>
@endsection